from datetime import time

DB_PATH = "intraday.db"

CAPITAL = 100_000
RISK_PER_TRADE = 0.01

ENTRY_WINDOW_START = time(9, 45)
ENTRY_WINDOW_END = time(10, 15)

NIFTY_INDEX_TICKER = "^NSEI"

NIFTY_STOCKS = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "KOTAKBANK.NS", "AXISBANK.NS", "LT.NS", "SBIN.NS", "HINDUNILVR.NS",
    "ITC.NS", "BAJFINANCE.NS", "BHARTIARTL.NS", "ASIANPAINT.NS",
    "HCLTECH.NS", "WIPRO.NS", "ULTRACEMCO.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS"
]
